### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ashrond** [PowerShellCrack/LGPOPSmodule#1]
Can you provide an example of how to properly call this module?
I am having difficulty with the syntax.

...sorry for being dense

**Comment by PowerShellCrack** [comment]
Yeah I need to add a synopsis to this and a better README. But anyway run it like this:

`
Set-SystemSetting -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\ImmersiveShell' -Name 'UseActionCenterExperience' -Type DWord -Value 0 -Force -TryLGPO:$True -LGPOBinaryPath c:\windows\temp\LGPO.exe

   
Set-UserSetting -Path 'SOFTWARE\Policies\Microsoft\Windows\Explorer' -Name 'DisableNotificationCenter' -Type DWord -Value 1 -Force -TryLGPO:$True -LGPOBinaryPath c:\windows\temp\LGPO.exe
`

You will need to specify the path to the LGPO.exe file.

**Comment by PowerShellCrack** [comment]
I've updated the module and it is now in Powershellgallery. Please review the README for how to.

**Comment by ashrond** [comment]
Thank you for the update on how to/syntax
I have updated my script and I am getting no errors; however I am not seeing any changes applied.
Here is the relevant section of the script, after I have installed RSAT packages.
The Payload.zip file contains LGPO.exe and your LGPOPS module-master

I feel it must be something that I am doing incorrectly, but I do not see it.




Thanks,

**Comment by PowerShellCrack** [comment]
Most likely you didn't do anything incorrectly. When I get time this week, I will review your code and try to do the same on my system.

I've also updated the module to add the cmdlets to ExportCommands. Try it again but install it from PowerShell gallery. Before it was missing the cmdlets. Run this to update the module:

1. Uninstall-Module LGPO -AllVersions
2. Install-Module LGPO -Force
3. Import-Module LGPO
4. Get-Module -Name LGPO

**Comment by ashrond** [comment]
Thank you,
Ill dig into this tonight, unfortunately however, I am unable to install from the internet in this case, so I am pre-downloading the files. Will that break the process?

Thanks,

**Comment by PowerShellCrack** [comment]
I've updated this repo as well. It Should work

**Comment by ashrond** [comment]
I am still not seeing the policy change, however I do see the module being called and reporting that it is running successfully.
despite uninstalling all versions, I do see 2 versions reported when I call the module, 1.0.2.2 and 0.0
I still feel that I am missing something here 

see attached:
![output1](https://user-images.githubusercontent.com/1237572/157747311-e49f85a0-388b-4ead-96b4-88dc631000aa.PNG)

**Comment by PowerShellCrack** [comment]
Your not setting registry items; your trying to call an item in the administrative template path. This module is designed to take a registry key and set it that administrative template item; not the other way around. 

For instance:
You trying to set this policy: 

`Computer Configuration > Administrative Templates > Windows Components > Push To Install` 

to disabled right?

So you want to run the registry key for it: 

`Set-LocalPolicySetting -Path 'HKLM:\SOFTWARE\Policies\Microsoft\PushToInstall' -Name 'DisablePushToInstall' -Type DWord -Value 0`

**Comment by PowerShellCrack** [comment]
I bet it did set some invalid registry keys though from that screenshot; you might want to check those. Also check group policy extra registry items in **gpresult /r**. But now I'm thinking i need to right a module that gets the registry from an administrative template.....hmmmm

**Comment by ashrond** [comment]
> Your not setting registry items; your trying to call an item in the administrative template path. This module is designed to take a registry key and set it that administrative template item; not the other way around.
> 
> For instance: You trying to set this policy:
> 
> `Computer Configuration > Administrative Templates > Windows Components > Push To Install`
> 
> to disabled right?
> 
> So you want to run the registry key for it:
> 
> `Set-LocalPolicySetting -Path 'HKLM:\SOFTWARE\Policies\Microsoft\PushToInstall' -Name 'DisablePushToInstall' -Type DWord -Value 0`

DERP

I'm an idiot sometimes... I was trying to use this to change the local sec policy, which currently has the PushToInstall service, Disabled. It seems that I have just taken the long road around to come back to square 1. Lucky I'm working on a test VM, so no long term damage by this...

I did try your suggestion, but the service is still being stopped from starting. :/

any ideas?

**Comment by PowerShellCrack** [comment]
Are you trying to stop it or start it? I would try to do something like [https://www.grouppolicy.biz/2010/08/how-to-use-group-policy-to-control-services/](this)

Otherwise if your trying to do it programmatically, try PowerShell commands:

To stop and disable it:

`Get-Service PushToInstall | Set-Service -StartupType Disabled`
`Stop-Service PushToInstall -Force`

To start it:

`Get-Service PushToInstall | Set-Service -StartupType Automatic`
`Start-Service PushToInstall -Force`


BTW: Are you a Knight-Rider fan? I saw your repo. I used to own two KITT cars.

**Comment by ashrond** [comment]
I need to disable the LGPO that is explicitly preventing the service from starting. Scripting it to stat or set to auto/delayed start is pretty easy. Unfortunately, were not using a DC and we really should be at this point. I was hoping to find a way to script LGPO changes easily without the need to import, export, or transport new policies between machines.

On the KR question, yes, yes I am 😃
I have a few projects that orbit that topic, including an openauto build running on a pi4, I was sampling ki3t’s voice to generate a speech profile to tie into something like an open version of alexa to run in the background, and I have just received the proto boards for the scanner bar control box.


Thanks,

**Comment by PowerShellCrack** [comment]
So.... that can also be managed by LGPO using a security template though (eg. GptTmpl.inf). I wrote a similar script to utilize the LGPO as well in this repo [https://github.com/PowerShellCrack/STIGSCAPWinTool](url) but I don't think it will help. 

in summary LGPO can be ran like this:

`LGPO.exe /s <pathtofile>\gptTmpl.inf`

The inf file is formatted like this

`[Unicode]`
`Unicode=yes`
`[Version]`
`signature="$CHICAGO$"`
`Revision=1`
`[Service General Setting]`
`"PushToInstall",4,""`

Change the **4** to a **2** and save file call it by _LGPO /s_

I could write this into the module to support these types of configs, but it would have to be sometime this weekend or next. 

here are some screenshots
![pushtoinstall_disabled](https://user-images.githubusercontent.com/20599825/157885568-062665d1-286c-4f06-b8a3-f23200e4e393.jpg)

![pushtoinstall_auto](https://user-images.githubusercontent.com/20599825/157885614-bb3ffc27-5307-4812-92c5-6267059fa9b2.jpg)

**Comment by PowerShellCrack** [comment]
keep in mind; the only way to reset a service or any policy for that matter is not to set it as _not configured_ but to set it the opposite, apply the policy, then remove the policy. Otherwise, if you remove the policy in the state it's in it will stay in that state. 

For example, your current security template that's applied to your windows device is set to **disable** the _PushtoInstall_ service. If you removed the service from the security template (eg. gpttmpl.inf), the service will stay disabled and would have to be manually enabled (which can be done now that there is no policy for it). However, if you apply a new policy that starts service, then the service will start up and THEN you can remove the policy. 

Here is the next problem. A security template can be layered like group policy can, but when using LGPO, it only sees what's being applied. If you want other services to have a policy against them but not the _PushToInstall_ one, then for LGPO, you would have to "inventory" all services affected by the policy and then remove the one you want, then reapply the policy. that can be done programmatically but allot of effort is needed to ensure its accurate.

**Comment by ashrond** [comment]
> So.... that can also be managed by LGPO using a security template though (eg. GptTmpl.inf). I wrote a similar script to utilize the LGPO as well in this repo [https://github.com/PowerShellCrack/STIGSCAPWinTool](url) but I don't think it will help.
> 
> in summary LGPO can be ran like this:
> 
> `LGPO.exe /s <pathtofile>\gptTmpl.inf`
> 
> The inf file is formatted like this
> 
> `[Unicode]` `Unicode=yes` `[Version]` `signature="$CHICAGO$"` `Revision=1` `[Service General Setting]` `"PushToInstall",4,""`
> 
> Change the **4** to a **2** and save file call it by _LGPO /s_
> 
> I could write this into the module to support these types of configs, but it would have to be sometime this weekend or next.
> 
> here are some screenshots ![pushtoinstall_disabled](https://user-images.githubusercontent.com/20599825/157885568-062665d1-286c-4f06-b8a3-f23200e4e393.jpg)
> 
> ![pushtoinstall_auto](https://user-images.githubusercontent.com/20599825/157885614-bb3ffc27-5307-4812-92c5-6267059fa9b2.jpg)

ok, i just created the inf file in npp as displayed and attempted to apply it with lgpo.exe /s, it keeps erroring out with exit code 1. also, get-service is not recognized. i am wondering if i dont have something installed that is required.

also, what is the signature value $CHICHAGO$?

**Comment by ashrond** [comment]
hey, I really appreciate all the help on this. I am going to put in some time this weekend to look at doing this more thoroughly, as we have quite a large security policy and as you ment6ioned I need to go over it to verify it.

**Comment by PowerShellCrack** [comment]
Looks like problem is solved.
