### ISSUE TITLE
Functions aren't recognized

### ISSUE THREAD

**Issue by xalso** [PowerShellCrack/LGPOPSmodule#2]
Hi All,
After install module LGPO I have error that functions aren't recognized. Did you have similar issue? What should I do?

**Comment by PowerShellCrack** [comment]
I've updated the module to add the cmdlets to ExportCommends. Run this to update the module:

1. Uninstall-Module LGPO -AllVersions
2. Install-Module LGPO -Force
3. Import-Module LGPO
4. Get-Module -Name LGPO

**Comment by PowerShellCrack** [comment]
Did this work?

**Comment by xalso** [comment]
Thank you for help. It started working.
